import BasicText from './BasicText.vue';
import Blank from './Blank.vue';
import ColorPalette from './ColorPalette.vue';
import DoubleImage from './DoubleImage.vue';
import Download from './Download.vue';
import FeBlank from './FeBlank.vue';
import FeColorPalette from './FeColorPalette.vue';
import FeDownload from './FeDownload.vue';
import FeMedia from './FeMedia.vue';
import FeResource from './FeResource.vue';
import FeSlider from './FeSlider.vue';
import FeTitleText from './FeTitleText.vue';
import Media from './Media.vue';
import ModuleGroup from './ModuleGroup.vue';
import Resource from './Resource.vue';
import Slider from './Slider.vue';
import TitleText from './TitleText.vue';
export const getComponentsMap = (): Record<string, any> => ({ BasicText, Blank, ColorPalette, DoubleImage, Download, FeBlank, FeColorPalette, FeDownload, FeMedia, FeResource, FeSlider, FeTitleText, Media, ModuleGroup, Resource, Slider, TitleText });